In [0]:
import numpy as np
import pandas as pd

In [118]:
X=np.array([[1,1,1,0],[0,1,1,1],[1,1,0,1],[1,1,0,0]])
X

array([[1, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 0, 0]])

In [119]:
M = len(X)     # number of x vectors
N = len(X[0])
print(M)
print(N)

4
4


In [120]:
W=np.array([[0.2,0.4,0.7,0.8],[0.1,0.3,0.5,0.9]])
W=np.transpose(W)
W

array([[0.2, 0.1],
       [0.4, 0.3],
       [0.7, 0.5],
       [0.8, 0.9]])

In [0]:
def distance(w, x):
    r = np.zeros(W.shape)
    for i in range(M):
        for j in range(len(w)):
            r[i] = r[i] + (w[i] - x[i][j])*(w[i] - x[i][j])
    
    return r

In [122]:
distance(W,X)

array([[1.96, 2.44],
       [1.24, 1.56],
       [0.76, 1.  ],
       [1.36, 1.64]])

In [0]:
def FindClosest(W,X):
     y=distance(W,X)
     z=np.zeros(W.shape[0])

     for i in range(M):
         if(y[i][0]<y[i][1]):
             z[i]=1
         else:
            z[i]=2

     return z

    

In [124]:
FindClosest(W,X)

array([1., 1., 1., 1.])

In [125]:
la=0.5
epoch=1
for k in range(epoch):
    z=FindClosest(W,X)
    for i in range (M):
        for j in range(N):
            if(z[i]==1):
                W[i][0] = W[i][0] + la * (X[i][j] - W[i][0])
                
            else:
                W[i][1] = W[i][1] + la * (X[i][j] - W[i][1]) 
print(W)
                

[[0.45    0.1    ]
 [0.9     0.3    ]
 [0.73125 0.5    ]
 [0.2375  0.9    ]]
