In [0]:
import numpy as np
import pandas as pd

In [126]:
X=np.array([[-1,-1],[-1,1],[1,-1],[1,1]])
X

array([[-1, -1],
       [-1,  1],
       [ 1, -1],
       [ 1,  1]])

In [127]:
O=np.array([-1,-1,-1,1])
O=np.transpose(O)
O


array([-1, -1, -1,  1])

In [128]:
# W=np.random.random([X.shape[1]])
# b=np.random.random(1)
W=np.array([1,0])
b=0
print(W,b)

[1 0] 0


In [129]:
sum=np.zeros(O.shape)
sum

array([0., 0., 0., 0.])

In [0]:
def step(sum):
    if (sum>0.5):
        return 1
    elif(sum<-0.5):
        return -1
    else:
        return 0

In [0]:
n_epoch=5
learning_rate=1

In [132]:
for k in range (n_epoch):
    c=0
    for i in range(4):
        sum[i] = step(X[i][0]*W[0] + X[i][1]*W[1] +b)
        print(sum[i])
        print(X[i])
        print(O[i])
        if(sum[i]!=O[i]):
            print("HI")
            W[0]=W[0]+learning_rate*O[i]*X[i][0]
            W[1]=W[1]+learning_rate*O[i]*X[i][1]
            b=b+learning_rate*O[i]
        print(b)

-1.0
[-1 -1]
-1
0
-1.0
[-1  1]
-1
0
1.0
[ 1 -1]
-1
HI
-1
0.0
[1 1]
1
HI
0
-1.0
[-1 -1]
-1
0
1.0
[-1  1]
-1
HI
-1
0.0
[ 1 -1]
-1
HI
-2
1.0
[1 1]
1
-2
-1.0
[-1 -1]
-1
-2
-1.0
[-1  1]
-1
-2
-1.0
[ 1 -1]
-1
-2
1.0
[1 1]
1
-2
-1.0
[-1 -1]
-1
-2
-1.0
[-1  1]
-1
-2
-1.0
[ 1 -1]
-1
-2
1.0
[1 1]
1
-2
-1.0
[-1 -1]
-1
-2
-1.0
[-1  1]
-1
-2
-1.0
[ 1 -1]
-1
-2
1.0
[1 1]
1
-2


In [133]:
W

array([1, 2])

In [134]:
b

-2